# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SF Tech Drysuits
email: chris@sftech.ch
description: >- # this means to ignore newlines until "baseurl:"
  Heavy duty drysuits for recreational, technical and commercial divers, made in Switzerland
baseurl: '' # the subpath of your site, e.g. /blog
# url: 'https://www.sftech.ch' # the base hostname & protocol for your site, e.g. http://example.com
url: 'http://localhost:4000' # the base hostname & protocol for your site, e.g. http://example.com
# url: 'http://192.168.1.40:4000' # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Languages
languages: ['en', 'fr', 'de']
defaultLang: en
languageNames:
  en: English
  fr: Francais
  de: Deutsch
  ru: Russian
  cn: Chinese
  kr: Korean

# Build Settings
# sass:                 sass preprocessor is now done with gulp
#   sass_dir: _scss
include: ['_pages']

exclude:
  [
    '_src',
    '_sass',
    'node_modules',
    'gulpfile.js',
    'feed.xml',
    'Gemfile',
    'Gemfile.lock',
    'package-lock.json',
    'package.json',
    'redirects.json',
  ]

keep_files: [assets]

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  # Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
