url: 'http://localhost:4000' # the base hostname & protocol for your site, e.g. http://example.com
# url: 'http://192.168.1.40:4000' # the base hostname & protocol for your site, e.g. http://example.com
